name: Aviator Scraper

on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes
  workflow_dispatch:       # Allows manual run from GitHub

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install --upgrade pip

      - name: Run Python Script
        run: python main.py

      - name: Commit updated multipliers
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add results.json
          git commit -m "Update multipliers"
          git push
